spring.application.name=neometroapi

server.port=8083

spring.neo4j.uri=bolt://localhost:7687
spring.data.neo4j.database=metro
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neo4j

azure.application-insights.instrumentation-key=da439520-e460-4da5-ba6a-e5e0287f8b94
APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=da439520-e460-4da5-ba6a-e5e0287f8b94;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com

azure.application-insights.telemetry.enabled=true
azure.application-insights.default-modules.enabled=true

applicationinsights.logger.level=TRACE



