spring.application.name=neometroapi


server.port=8083

spring.neo4j.uri=bolt://localhost:7687
spring.data.neo4j.database=metro
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neo4j

#azure.application-insights.instrumentation-key=<ENTER_KEY_HERE>
#APPLICATIONINSIGHTS_CONNECTION_STRING=InstrumentationKey=<ENTER_KEY_HERE>;IngestionEndpoint=https://eastus-8.in.applicationinsights.azure.com

azure.application-insights.telemetry.enabled=true
azure.application-insights.default-modules.enabled=true
applicationinsights.logger.level=TRACE


#springdoc.api-docs.path=/v3/api-docs
#springdoc.swagger-ui.path=/swagger-ui.html

# OpenAI configuration
#spring.ai.openai.api-key=<ENTER_KEY_HERE>
#spring.ai.openai.chat.options.model=gpt-4

# Enable MCP server
spring.mcp.server.enabled=true

# Enable MCP API
spring.ai.mcp.api.enabled=true

spring.mcp.server.path=/v1
spring.mcp.server.api-name=openai

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ai=DEBUG







